import QtQuick
import "nowplaying"
import ".."

// Data host for the now-playing page. This file owns the track, the lyrics
// fetch and the tab state; nowplaying/ owns the look and nothing else.
Item {
    id: pane
    // ON SCREEN once, at the first frame the window swaps after this page
    // is shown: the page's first build stalls the thread, and the bar's
    // layout swap waits for this rather than guessing at the stall
    property bool onScreen: false
    Connections {
        target: pane.visible && !pane.onScreen ? FrameClock : null
        function onSwapped(title) { if (pane.Window.window && title === pane.Window.window.title) pane.onScreen = true }
    }
    clip: true

    readonly property var track: PlayerState.currentTrack
    readonly property string vid: track ? (track.id || "") : ""
    readonly property string art: track ? (track.thumbnail || "") : ""
    readonly property string title: track ? (track.title || "") : ""
    readonly property string channel: track ? (track.channel || "") : ""
    readonly property var info: PlayerState.trackInfo

    property int tab: 0             // 0 info, 1 lyrics — the record's column
    // The ends have no column to put a second thing in, so the words are a
    // plain on/off there rather than the other half of a choice.
    property bool showWords: false
    property var lines: []          // [{ t, text }] when the source was timed
    property string plain: ""
    property bool autoGenerated: false
    property bool loading: false
    property string loadedFor: ""
    readonly property bool hasWords: lines.length > 0 || plain.length > 0
    // We only know there are none once the fetch has come back for THIS track;
    // until then the tab is a live offer.
    readonly property bool noLyrics: vid.length > 0 && loadedFor === vid
                                     && !loading && !hasWords
    readonly property string description: info.description || ""

    // ---- shared formatting the styles draw from ------------------------
    function fmtTime(s) {
        if (!isFinite(s) || s <= 0) return ""
        const m = Math.floor(s / 60), sec = Math.floor(s % 60)
        return m + ":" + (sec < 10 ? "0" : "") + sec
    }
    // one dim line of everything worth saying in passing
    readonly property string metaLine: {
        const parts = []
        const d = fmtTime(PlayerState.duration)
        if (d) parts.push(d)
        // viewsShort is the unit-free "1.8B" when YouTube gives one, and the
        // whole "1,809,880,871 views" when it does not, so "views" is added
        // only when missing.
        if (info.viewsShort)
            parts.push(/views/i.test(info.viewsShort) ? info.viewsShort
                                                      : info.viewsShort + " views")
        if (info.likes) parts.push(info.likes + " likes")
        if (info.published) parts.push(info.published)
        return parts.join("   ·   ")
    }
    // label/value pairs, for the styles that lay the facts out as a list
    readonly property var facts: {
        const f = []
        const d = fmtTime(PlayerState.duration)
        if (d) f.push({ k: "Length", v: d })
        if (info.views) f.push({ k: "Views", v: info.views })
        if (info.likes) f.push({ k: "Likes", v: info.likes })
        if (info.published) f.push({ k: "Published", v: info.published })
        if (info.subscribers) f.push({ k: "Channel", v: info.subscribers })
        return f
    }
    readonly property string emptyBody: !vid ? "Nothing playing"
        : (tab === 1 && !hasWords && !loading) ? "No lyrics"
        : (tab === 0 && !description.length && !facts.length) ? "No info"
        : ""

    function seekTo(t) { Player.seek(t) }

    function load() {
        if ((tab !== 1 && !showWords) || !vid || vid === loadedFor) return
        loadedFor = vid
        lines = []; plain = ""; autoGenerated = false; loading = true
        const t = track || {}
        sidecar.rpc("lyrics/get", { videoId: vid,
                                    artist: t.channel || "", title: t.title || "",
                                    duration: PlayerState.duration || 0 }, (r) => {
            if (pane.loadedFor !== vid) return   // the track moved on
            pane.loading = false
            const res = r.ok ? r.result : null
            pane.lines = res && res.lines ? res.lines : []
            pane.plain = res && res.plain ? res.plain : ""
            pane.autoGenerated = !!(res && res.autoGenerated)
        })
    }
    // a new track drops the old words; they reload only if the tab is open
    onVidChanged: {
        lines = []; plain = ""; autoGenerated = false
        loading = false; loadedFor = ""
        if (visible) load()
    }
    // Once a fetch comes back with nothing, the lyrics choice falls back to
    // what there is; the greyed tab says why.
    onNoLyricsChanged: if (noLyrics) { if (tab === 1) tab = 0; showWords = false }

    onTabChanged: if (visible) load()
    onShowWordsChanged: if (visible) load()
    onVisibleChanged: {
        if (visible) load()
        if (visible && !onScreen && Window.window && !FrameClock.exposed(Window.window.title)) onScreen = true   // an unexposed window swaps nothing
    }

    readonly property int activeLine: {
        if (!lines.length) return -1
        const p = PlayerState.position
        let i = -1
        for (let k = 0; k < lines.length; k++) {
            if (lines[k].t <= p) i = k
            else break
        }
        return i
    }

    // ---- the page --------------------------------------------------------
    // One page, in three stops: the artwork as a poster, the record out of its
    // sleeve, and the plain cover page. Poster owns all of it.
    readonly property Item styleItem: page
    Poster {
        id: page
        objectName: "npPoster"
        anchors.fill: parent
        np: pane
    }
}
